/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopUsersRouteImport } from './routes/top-users'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsReconciledVeterinarianContractsRouteImport } from './routes/reports/reconciled-veterinarian-contracts'
import { Route as ReportsFoodSupplierContractsRouteImport } from './routes/reports/food-supplier-contracts'
import { Route as ReportsComplementaryServiceContractsRouteImport } from './routes/reports/complementary-service-contracts'
import { Route as ReportsAnimalCareScheduleRouteImport } from './routes/reports/animal-care-schedule'
import { Route as ReportsActiveVeterinariansRouteImport } from './routes/reports/active-veterinarians'

const TopUsersRoute = TopUsersRouteImport.update({
  id: '/top-users',
  path: '/top-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReconciledVeterinarianContractsRoute =
  ReportsReconciledVeterinarianContractsRouteImport.update({
    id: '/reports/reconciled-veterinarian-contracts',
    path: '/reports/reconciled-veterinarian-contracts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsFoodSupplierContractsRoute =
  ReportsFoodSupplierContractsRouteImport.update({
    id: '/reports/food-supplier-contracts',
    path: '/reports/food-supplier-contracts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsComplementaryServiceContractsRoute =
  ReportsComplementaryServiceContractsRouteImport.update({
    id: '/reports/complementary-service-contracts',
    path: '/reports/complementary-service-contracts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsAnimalCareScheduleRoute =
  ReportsAnimalCareScheduleRouteImport.update({
    id: '/reports/animal-care-schedule',
    path: '/reports/animal-care-schedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsActiveVeterinariansRoute =
  ReportsActiveVeterinariansRouteImport.update({
    id: '/reports/active-veterinarians',
    path: '/reports/active-veterinarians',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/profit': typeof ProfitRoute
  '/top-users': typeof TopUsersRoute
  '/reports/active-veterinarians': typeof ReportsActiveVeterinariansRoute
  '/reports/animal-care-schedule': typeof ReportsAnimalCareScheduleRoute
  '/reports/complementary-service-contracts': typeof ReportsComplementaryServiceContractsRoute
  '/reports/food-supplier-contracts': typeof ReportsFoodSupplierContractsRoute
  '/reports/reconciled-veterinarian-contracts': typeof ReportsReconciledVeterinarianContractsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/profit': typeof ProfitRoute
  '/top-users': typeof TopUsersRoute
  '/reports/active-veterinarians': typeof ReportsActiveVeterinariansRoute
  '/reports/animal-care-schedule': typeof ReportsAnimalCareScheduleRoute
  '/reports/complementary-service-contracts': typeof ReportsComplementaryServiceContractsRoute
  '/reports/food-supplier-contracts': typeof ReportsFoodSupplierContractsRoute
  '/reports/reconciled-veterinarian-contracts': typeof ReportsReconciledVeterinarianContractsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/profit': typeof ProfitRoute
  '/top-users': typeof TopUsersRoute
  '/reports/active-veterinarians': typeof ReportsActiveVeterinariansRoute
  '/reports/animal-care-schedule': typeof ReportsAnimalCareScheduleRoute
  '/reports/complementary-service-contracts': typeof ReportsComplementaryServiceContractsRoute
  '/reports/food-supplier-contracts': typeof ReportsFoodSupplierContractsRoute
  '/reports/reconciled-veterinarian-contracts': typeof ReportsReconciledVeterinarianContractsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/profit'
    | '/top-users'
    | '/reports/active-veterinarians'
    | '/reports/animal-care-schedule'
    | '/reports/complementary-service-contracts'
    | '/reports/food-supplier-contracts'
    | '/reports/reconciled-veterinarian-contracts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/profit'
    | '/top-users'
    | '/reports/active-veterinarians'
    | '/reports/animal-care-schedule'
    | '/reports/complementary-service-contracts'
    | '/reports/food-supplier-contracts'
    | '/reports/reconciled-veterinarian-contracts'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/profit'
    | '/top-users'
    | '/reports/active-veterinarians'
    | '/reports/animal-care-schedule'
    | '/reports/complementary-service-contracts'
    | '/reports/food-supplier-contracts'
    | '/reports/reconciled-veterinarian-contracts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  ProfitRoute: typeof ProfitRoute
  TopUsersRoute: typeof TopUsersRoute
  ReportsActiveVeterinariansRoute: typeof ReportsActiveVeterinariansRoute
  ReportsAnimalCareScheduleRoute: typeof ReportsAnimalCareScheduleRoute
  ReportsComplementaryServiceContractsRoute: typeof ReportsComplementaryServiceContractsRoute
  ReportsFoodSupplierContractsRoute: typeof ReportsFoodSupplierContractsRoute
  ReportsReconciledVeterinarianContractsRoute: typeof ReportsReconciledVeterinarianContractsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top-users': {
      id: '/top-users'
      path: '/top-users'
      fullPath: '/top-users'
      preLoaderRoute: typeof TopUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/reconciled-veterinarian-contracts': {
      id: '/reports/reconciled-veterinarian-contracts'
      path: '/reports/reconciled-veterinarian-contracts'
      fullPath: '/reports/reconciled-veterinarian-contracts'
      preLoaderRoute: typeof ReportsReconciledVeterinarianContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/food-supplier-contracts': {
      id: '/reports/food-supplier-contracts'
      path: '/reports/food-supplier-contracts'
      fullPath: '/reports/food-supplier-contracts'
      preLoaderRoute: typeof ReportsFoodSupplierContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/complementary-service-contracts': {
      id: '/reports/complementary-service-contracts'
      path: '/reports/complementary-service-contracts'
      fullPath: '/reports/complementary-service-contracts'
      preLoaderRoute: typeof ReportsComplementaryServiceContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/animal-care-schedule': {
      id: '/reports/animal-care-schedule'
      path: '/reports/animal-care-schedule'
      fullPath: '/reports/animal-care-schedule'
      preLoaderRoute: typeof ReportsAnimalCareScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/active-veterinarians': {
      id: '/reports/active-veterinarians'
      path: '/reports/active-veterinarians'
      fullPath: '/reports/active-veterinarians'
      preLoaderRoute: typeof ReportsActiveVeterinariansRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  ProfitRoute: ProfitRoute,
  TopUsersRoute: TopUsersRoute,
  ReportsActiveVeterinariansRoute: ReportsActiveVeterinariansRoute,
  ReportsAnimalCareScheduleRoute: ReportsAnimalCareScheduleRoute,
  ReportsComplementaryServiceContractsRoute:
    ReportsComplementaryServiceContractsRoute,
  ReportsFoodSupplierContractsRoute: ReportsFoodSupplierContractsRoute,
  ReportsReconciledVeterinarianContractsRoute:
    ReportsReconciledVeterinarianContractsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
