/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TopUsersRouteImport } from "./routes/top-users";
import { Route as ProfitRouteImport } from "./routes/profit";
import { Route as EventsRouteImport } from "./routes/events";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ContractsIndexRouteImport } from "./routes/contracts/index";
import { Route as ClinicsIndexRouteImport } from "./routes/clinics/index";
import { Route as AnimalsIndexRouteImport } from "./routes/animals/index";
import { Route as AdoptionsIndexRouteImport } from "./routes/adoptions/index";
import { Route as ReportsRevenuePlanRouteImport } from "./routes/reports/revenue-plan";
import { Route as ReportsReconciledVeterinarianContractsRouteImport } from "./routes/reports/reconciled-veterinarian-contracts";
import { Route as ReportsFoodSupplierContractsRouteImport } from "./routes/reports/food-supplier-contracts";
import { Route as ReportsComplementaryServiceContractsRouteImport } from "./routes/reports/complementary-service-contracts";
import { Route as ReportsAnimalCareScheduleRouteImport } from "./routes/reports/animal-care-schedule";
import { Route as ReportsActiveVeterinariansRouteImport } from "./routes/reports/active-veterinarians";
import { Route as ContractsNewRouteImport } from "./routes/contracts/new";
import { Route as ClinicsNewRouteImport } from "./routes/clinics/new";
import { Route as AnimalsNewRouteImport } from "./routes/animals/new";
import { Route as AdoptionsNewRouteImport } from "./routes/adoptions/new";
import { Route as ContractsContractIdEditRouteImport } from "./routes/contracts/$contractId.edit";
import { Route as ClinicsClinicIdEditRouteImport } from "./routes/clinics/$clinicId.edit";
import { Route as AnimalsAnimalIdEditRouteImport } from "./routes/animals/$animalId.edit";
import { Route as AdoptionsAdoptionIdEditRouteImport } from "./routes/adoptions/$adoptionId.edit";

const TopUsersRoute = TopUsersRouteImport.update({
  id: "/top-users",
  path: "/top-users",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfitRoute = ProfitRouteImport.update({
  id: "/profit",
  path: "/profit",
  getParentRoute: () => rootRouteImport,
} as any);
const EventsRoute = EventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: "/contracts/",
  path: "/contracts/",
  getParentRoute: () => rootRouteImport,
} as any);
const ClinicsIndexRoute = ClinicsIndexRouteImport.update({
  id: "/clinics/",
  path: "/clinics/",
  getParentRoute: () => rootRouteImport,
} as any);
const AnimalsIndexRoute = AnimalsIndexRouteImport.update({
  id: "/animals/",
  path: "/animals/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdoptionsIndexRoute = AdoptionsIndexRouteImport.update({
  id: "/adoptions/",
  path: "/adoptions/",
  getParentRoute: () => rootRouteImport,
} as any);
const ReportsRevenuePlanRoute = ReportsRevenuePlanRouteImport.update({
  id: "/reports/revenue-plan",
  path: "/reports/revenue-plan",
  getParentRoute: () => rootRouteImport,
} as any);
const ReportsReconciledVeterinarianContractsRoute =
  ReportsReconciledVeterinarianContractsRouteImport.update({
    id: "/reports/reconciled-veterinarian-contracts",
    path: "/reports/reconciled-veterinarian-contracts",
    getParentRoute: () => rootRouteImport,
  } as any);
const ReportsFoodSupplierContractsRoute =
  ReportsFoodSupplierContractsRouteImport.update({
    id: "/reports/food-supplier-contracts",
    path: "/reports/food-supplier-contracts",
    getParentRoute: () => rootRouteImport,
  } as any);
const ReportsComplementaryServiceContractsRoute =
  ReportsComplementaryServiceContractsRouteImport.update({
    id: "/reports/complementary-service-contracts",
    path: "/reports/complementary-service-contracts",
    getParentRoute: () => rootRouteImport,
  } as any);
const ReportsAnimalCareScheduleRoute =
  ReportsAnimalCareScheduleRouteImport.update({
    id: "/reports/animal-care-schedule",
    path: "/reports/animal-care-schedule",
    getParentRoute: () => rootRouteImport,
  } as any);
const ReportsActiveVeterinariansRoute =
  ReportsActiveVeterinariansRouteImport.update({
    id: "/reports/active-veterinarians",
    path: "/reports/active-veterinarians",
    getParentRoute: () => rootRouteImport,
  } as any);
const ContractsNewRoute = ContractsNewRouteImport.update({
  id: "/contracts/new",
  path: "/contracts/new",
  getParentRoute: () => rootRouteImport,
} as any);
const ClinicsNewRoute = ClinicsNewRouteImport.update({
  id: "/clinics/new",
  path: "/clinics/new",
  getParentRoute: () => rootRouteImport,
} as any);
const AnimalsNewRoute = AnimalsNewRouteImport.update({
  id: "/animals/new",
  path: "/animals/new",
  getParentRoute: () => rootRouteImport,
} as any);
const AdoptionsNewRoute = AdoptionsNewRouteImport.update({
  id: "/adoptions/new",
  path: "/adoptions/new",
  getParentRoute: () => rootRouteImport,
} as any);
const ContractsContractIdEditRoute = ContractsContractIdEditRouteImport.update({
  id: "/contracts/$contractId/edit",
  path: "/contracts/$contractId/edit",
  getParentRoute: () => rootRouteImport,
} as any);
const ClinicsClinicIdEditRoute = ClinicsClinicIdEditRouteImport.update({
  id: "/clinics/$clinicId/edit",
  path: "/clinics/$clinicId/edit",
  getParentRoute: () => rootRouteImport,
} as any);
const AnimalsAnimalIdEditRoute = AnimalsAnimalIdEditRouteImport.update({
  id: "/animals/$animalId/edit",
  path: "/animals/$animalId/edit",
  getParentRoute: () => rootRouteImport,
} as any);
const AdoptionsAdoptionIdEditRoute = AdoptionsAdoptionIdEditRouteImport.update({
  id: "/adoptions/$adoptionId/edit",
  path: "/adoptions/$adoptionId/edit",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/events": typeof EventsRoute;
  "/profit": typeof ProfitRoute;
  "/top-users": typeof TopUsersRoute;
  "/adoptions/new": typeof AdoptionsNewRoute;
  "/animals/new": typeof AnimalsNewRoute;
  "/clinics/new": typeof ClinicsNewRoute;
  "/contracts/new": typeof ContractsNewRoute;
  "/reports/active-veterinarians": typeof ReportsActiveVeterinariansRoute;
  "/reports/animal-care-schedule": typeof ReportsAnimalCareScheduleRoute;
  "/reports/complementary-service-contracts": typeof ReportsComplementaryServiceContractsRoute;
  "/reports/food-supplier-contracts": typeof ReportsFoodSupplierContractsRoute;
  "/reports/reconciled-veterinarian-contracts": typeof ReportsReconciledVeterinarianContractsRoute;
  "/reports/revenue-plan": typeof ReportsRevenuePlanRoute;
  "/adoptions/": typeof AdoptionsIndexRoute;
  "/animals/": typeof AnimalsIndexRoute;
  "/clinics/": typeof ClinicsIndexRoute;
  "/contracts/": typeof ContractsIndexRoute;
  "/adoptions/$adoptionId/edit": typeof AdoptionsAdoptionIdEditRoute;
  "/animals/$animalId/edit": typeof AnimalsAnimalIdEditRoute;
  "/clinics/$clinicId/edit": typeof ClinicsClinicIdEditRoute;
  "/contracts/$contractId/edit": typeof ContractsContractIdEditRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/events": typeof EventsRoute;
  "/profit": typeof ProfitRoute;
  "/top-users": typeof TopUsersRoute;
  "/adoptions/new": typeof AdoptionsNewRoute;
  "/animals/new": typeof AnimalsNewRoute;
  "/clinics/new": typeof ClinicsNewRoute;
  "/contracts/new": typeof ContractsNewRoute;
  "/reports/active-veterinarians": typeof ReportsActiveVeterinariansRoute;
  "/reports/animal-care-schedule": typeof ReportsAnimalCareScheduleRoute;
  "/reports/complementary-service-contracts": typeof ReportsComplementaryServiceContractsRoute;
  "/reports/food-supplier-contracts": typeof ReportsFoodSupplierContractsRoute;
  "/reports/reconciled-veterinarian-contracts": typeof ReportsReconciledVeterinarianContractsRoute;
  "/reports/revenue-plan": typeof ReportsRevenuePlanRoute;
  "/adoptions": typeof AdoptionsIndexRoute;
  "/animals": typeof AnimalsIndexRoute;
  "/clinics": typeof ClinicsIndexRoute;
  "/contracts": typeof ContractsIndexRoute;
  "/adoptions/$adoptionId/edit": typeof AdoptionsAdoptionIdEditRoute;
  "/animals/$animalId/edit": typeof AnimalsAnimalIdEditRoute;
  "/clinics/$clinicId/edit": typeof ClinicsClinicIdEditRoute;
  "/contracts/$contractId/edit": typeof ContractsContractIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/events": typeof EventsRoute;
  "/profit": typeof ProfitRoute;
  "/top-users": typeof TopUsersRoute;
  "/adoptions/new": typeof AdoptionsNewRoute;
  "/animals/new": typeof AnimalsNewRoute;
  "/clinics/new": typeof ClinicsNewRoute;
  "/contracts/new": typeof ContractsNewRoute;
  "/reports/active-veterinarians": typeof ReportsActiveVeterinariansRoute;
  "/reports/animal-care-schedule": typeof ReportsAnimalCareScheduleRoute;
  "/reports/complementary-service-contracts": typeof ReportsComplementaryServiceContractsRoute;
  "/reports/food-supplier-contracts": typeof ReportsFoodSupplierContractsRoute;
  "/reports/reconciled-veterinarian-contracts": typeof ReportsReconciledVeterinarianContractsRoute;
  "/reports/revenue-plan": typeof ReportsRevenuePlanRoute;
  "/adoptions/": typeof AdoptionsIndexRoute;
  "/animals/": typeof AnimalsIndexRoute;
  "/clinics/": typeof ClinicsIndexRoute;
  "/contracts/": typeof ContractsIndexRoute;
  "/adoptions/$adoptionId/edit": typeof AdoptionsAdoptionIdEditRoute;
  "/animals/$animalId/edit": typeof AnimalsAnimalIdEditRoute;
  "/clinics/$clinicId/edit": typeof ClinicsClinicIdEditRoute;
  "/contracts/$contractId/edit": typeof ContractsContractIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/events"
    | "/profit"
    | "/top-users"
    | "/adoptions/new"
    | "/animals/new"
    | "/clinics/new"
    | "/contracts/new"
    | "/reports/active-veterinarians"
    | "/reports/animal-care-schedule"
    | "/reports/complementary-service-contracts"
    | "/reports/food-supplier-contracts"
    | "/reports/reconciled-veterinarian-contracts"
    | "/reports/revenue-plan"
    | "/adoptions/"
    | "/animals/"
    | "/clinics/"
    | "/contracts/"
    | "/adoptions/$adoptionId/edit"
    | "/animals/$animalId/edit"
    | "/clinics/$clinicId/edit"
    | "/contracts/$contractId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/events"
    | "/profit"
    | "/top-users"
    | "/adoptions/new"
    | "/animals/new"
    | "/clinics/new"
    | "/contracts/new"
    | "/reports/active-veterinarians"
    | "/reports/animal-care-schedule"
    | "/reports/complementary-service-contracts"
    | "/reports/food-supplier-contracts"
    | "/reports/reconciled-veterinarian-contracts"
    | "/reports/revenue-plan"
    | "/adoptions"
    | "/animals"
    | "/clinics"
    | "/contracts"
    | "/adoptions/$adoptionId/edit"
    | "/animals/$animalId/edit"
    | "/clinics/$clinicId/edit"
    | "/contracts/$contractId/edit";
  id:
    | "__root__"
    | "/"
    | "/events"
    | "/profit"
    | "/top-users"
    | "/adoptions/new"
    | "/animals/new"
    | "/clinics/new"
    | "/contracts/new"
    | "/reports/active-veterinarians"
    | "/reports/animal-care-schedule"
    | "/reports/complementary-service-contracts"
    | "/reports/food-supplier-contracts"
    | "/reports/reconciled-veterinarian-contracts"
    | "/reports/revenue-plan"
    | "/adoptions/"
    | "/animals/"
    | "/clinics/"
    | "/contracts/"
    | "/adoptions/$adoptionId/edit"
    | "/animals/$animalId/edit"
    | "/clinics/$clinicId/edit"
    | "/contracts/$contractId/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  EventsRoute: typeof EventsRoute;
  ProfitRoute: typeof ProfitRoute;
  TopUsersRoute: typeof TopUsersRoute;
  AdoptionsNewRoute: typeof AdoptionsNewRoute;
  AnimalsNewRoute: typeof AnimalsNewRoute;
  ClinicsNewRoute: typeof ClinicsNewRoute;
  ContractsNewRoute: typeof ContractsNewRoute;
  ReportsActiveVeterinariansRoute: typeof ReportsActiveVeterinariansRoute;
  ReportsAnimalCareScheduleRoute: typeof ReportsAnimalCareScheduleRoute;
  ReportsComplementaryServiceContractsRoute: typeof ReportsComplementaryServiceContractsRoute;
  ReportsFoodSupplierContractsRoute: typeof ReportsFoodSupplierContractsRoute;
  ReportsReconciledVeterinarianContractsRoute: typeof ReportsReconciledVeterinarianContractsRoute;
  ReportsRevenuePlanRoute: typeof ReportsRevenuePlanRoute;
  AdoptionsIndexRoute: typeof AdoptionsIndexRoute;
  AnimalsIndexRoute: typeof AnimalsIndexRoute;
  ClinicsIndexRoute: typeof ClinicsIndexRoute;
  ContractsIndexRoute: typeof ContractsIndexRoute;
  AdoptionsAdoptionIdEditRoute: typeof AdoptionsAdoptionIdEditRoute;
  AnimalsAnimalIdEditRoute: typeof AnimalsAnimalIdEditRoute;
  ClinicsClinicIdEditRoute: typeof ClinicsClinicIdEditRoute;
  ContractsContractIdEditRoute: typeof ContractsContractIdEditRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/top-users": {
      id: "/top-users";
      path: "/top-users";
      fullPath: "/top-users";
      preLoaderRoute: typeof TopUsersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profit": {
      id: "/profit";
      path: "/profit";
      fullPath: "/profit";
      preLoaderRoute: typeof ProfitRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/events": {
      id: "/events";
      path: "/events";
      fullPath: "/events";
      preLoaderRoute: typeof EventsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contracts/": {
      id: "/contracts/";
      path: "/contracts";
      fullPath: "/contracts/";
      preLoaderRoute: typeof ContractsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/clinics/": {
      id: "/clinics/";
      path: "/clinics";
      fullPath: "/clinics/";
      preLoaderRoute: typeof ClinicsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/animals/": {
      id: "/animals/";
      path: "/animals";
      fullPath: "/animals/";
      preLoaderRoute: typeof AnimalsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/adoptions/": {
      id: "/adoptions/";
      path: "/adoptions";
      fullPath: "/adoptions/";
      preLoaderRoute: typeof AdoptionsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reports/revenue-plan": {
      id: "/reports/revenue-plan";
      path: "/reports/revenue-plan";
      fullPath: "/reports/revenue-plan";
      preLoaderRoute: typeof ReportsRevenuePlanRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reports/reconciled-veterinarian-contracts": {
      id: "/reports/reconciled-veterinarian-contracts";
      path: "/reports/reconciled-veterinarian-contracts";
      fullPath: "/reports/reconciled-veterinarian-contracts";
      preLoaderRoute: typeof ReportsReconciledVeterinarianContractsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reports/food-supplier-contracts": {
      id: "/reports/food-supplier-contracts";
      path: "/reports/food-supplier-contracts";
      fullPath: "/reports/food-supplier-contracts";
      preLoaderRoute: typeof ReportsFoodSupplierContractsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reports/complementary-service-contracts": {
      id: "/reports/complementary-service-contracts";
      path: "/reports/complementary-service-contracts";
      fullPath: "/reports/complementary-service-contracts";
      preLoaderRoute: typeof ReportsComplementaryServiceContractsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reports/animal-care-schedule": {
      id: "/reports/animal-care-schedule";
      path: "/reports/animal-care-schedule";
      fullPath: "/reports/animal-care-schedule";
      preLoaderRoute: typeof ReportsAnimalCareScheduleRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reports/active-veterinarians": {
      id: "/reports/active-veterinarians";
      path: "/reports/active-veterinarians";
      fullPath: "/reports/active-veterinarians";
      preLoaderRoute: typeof ReportsActiveVeterinariansRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contracts/new": {
      id: "/contracts/new";
      path: "/contracts/new";
      fullPath: "/contracts/new";
      preLoaderRoute: typeof ContractsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/clinics/new": {
      id: "/clinics/new";
      path: "/clinics/new";
      fullPath: "/clinics/new";
      preLoaderRoute: typeof ClinicsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/animals/new": {
      id: "/animals/new";
      path: "/animals/new";
      fullPath: "/animals/new";
      preLoaderRoute: typeof AnimalsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/adoptions/new": {
      id: "/adoptions/new";
      path: "/adoptions/new";
      fullPath: "/adoptions/new";
      preLoaderRoute: typeof AdoptionsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contracts/$contractId/edit": {
      id: "/contracts/$contractId/edit";
      path: "/contracts/$contractId/edit";
      fullPath: "/contracts/$contractId/edit";
      preLoaderRoute: typeof ContractsContractIdEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/clinics/$clinicId/edit": {
      id: "/clinics/$clinicId/edit";
      path: "/clinics/$clinicId/edit";
      fullPath: "/clinics/$clinicId/edit";
      preLoaderRoute: typeof ClinicsClinicIdEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/animals/$animalId/edit": {
      id: "/animals/$animalId/edit";
      path: "/animals/$animalId/edit";
      fullPath: "/animals/$animalId/edit";
      preLoaderRoute: typeof AnimalsAnimalIdEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/adoptions/$adoptionId/edit": {
      id: "/adoptions/$adoptionId/edit";
      path: "/adoptions/$adoptionId/edit";
      fullPath: "/adoptions/$adoptionId/edit";
      preLoaderRoute: typeof AdoptionsAdoptionIdEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  ProfitRoute: ProfitRoute,
  TopUsersRoute: TopUsersRoute,
  AdoptionsNewRoute: AdoptionsNewRoute,
  AnimalsNewRoute: AnimalsNewRoute,
  ClinicsNewRoute: ClinicsNewRoute,
  ContractsNewRoute: ContractsNewRoute,
  ReportsActiveVeterinariansRoute: ReportsActiveVeterinariansRoute,
  ReportsAnimalCareScheduleRoute: ReportsAnimalCareScheduleRoute,
  ReportsComplementaryServiceContractsRoute:
    ReportsComplementaryServiceContractsRoute,
  ReportsFoodSupplierContractsRoute: ReportsFoodSupplierContractsRoute,
  ReportsReconciledVeterinarianContractsRoute:
    ReportsReconciledVeterinarianContractsRoute,
  ReportsRevenuePlanRoute: ReportsRevenuePlanRoute,
  AdoptionsIndexRoute: AdoptionsIndexRoute,
  AnimalsIndexRoute: AnimalsIndexRoute,
  ClinicsIndexRoute: ClinicsIndexRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  AdoptionsAdoptionIdEditRoute: AdoptionsAdoptionIdEditRoute,
  AnimalsAnimalIdEditRoute: AnimalsAnimalIdEditRoute,
  ClinicsClinicIdEditRoute: ClinicsClinicIdEditRoute,
  ContractsContractIdEditRoute: ContractsContractIdEditRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
