-- UUID primary keys and integer enumerations.
--
-- Hand-written so that existing databases keep their data: every integer key is
-- replaced by a generated UUID and every foreign key is re-pointed at the new
-- UUID of the row it referenced, before the integer columns are dropped. The
-- string enumerations are mapped to the SMALLINT values defined in
-- packages/schemas/src/enums.ts.
--
-- Constraint and index names match what Prisma generates for the schema, so
-- `prisma migrate diff` reports no drift afterwards. The UUID columns end with
-- no database default: `@default(uuid())` is generated by the Prisma client.

-- ---------------------------------------------------------------------------
-- 1. Drop the foreign keys that reference integer keys
-- ---------------------------------------------------------------------------

ALTER TABLE "Veterinarian" DROP CONSTRAINT "Veterinarian_id_supplier_fkey";
ALTER TABLE "Veterinarian" DROP CONSTRAINT "Veterinarian_id_clinic_fkey";
ALTER TABLE "Contract" DROP CONSTRAINT "Contract_id_supplier_fkey";
ALTER TABLE "TransportService" DROP CONSTRAINT "TransportService_id_contract_fkey";
ALTER TABLE "ServiceOffered" DROP CONSTRAINT "ServiceOffered_id_contract_fkey";
ALTER TABLE "Activity" DROP CONSTRAINT "Activity_id_animal_fkey";
ALTER TABLE "Activity" DROP CONSTRAINT "Activity_id_service_fkey";
ALTER TABLE "Adoption" DROP CONSTRAINT "Adoption_id_animal_fkey";
ALTER TABLE "Donation" DROP CONSTRAINT "Donation_id_animal_fkey";

-- ---------------------------------------------------------------------------
-- 2. Generate a UUID for every row of a table that owns its key
-- ---------------------------------------------------------------------------

ALTER TABLE "Clinic" ADD COLUMN "new_id" UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE "Supplier" ADD COLUMN "new_id" UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE "Contract" ADD COLUMN "new_id" UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE "ServiceOffered" ADD COLUMN "new_id" UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE "Animal" ADD COLUMN "new_id" UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE "Activity" ADD COLUMN "new_id" UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE "Adoption" ADD COLUMN "new_id" UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE "Donation" ADD COLUMN "new_id" UUID NOT NULL DEFAULT gen_random_uuid();

-- ---------------------------------------------------------------------------
-- 3. Re-point every reference at the UUID of the row it referenced
-- ---------------------------------------------------------------------------

ALTER TABLE "Veterinarian" ADD COLUMN "new_id_supplier" UUID, ADD COLUMN "new_id_clinic" UUID;
UPDATE "Veterinarian" AS v SET "new_id_supplier" = s."new_id"
  FROM "Supplier" AS s WHERE v."id_supplier" = s."id_supplier";
UPDATE "Veterinarian" AS v SET "new_id_clinic" = c."new_id"
  FROM "Clinic" AS c WHERE v."id_clinic" = c."id_clinic";

ALTER TABLE "Contract" ADD COLUMN "new_id_supplier" UUID;
UPDATE "Contract" AS ct SET "new_id_supplier" = s."new_id"
  FROM "Supplier" AS s WHERE ct."id_supplier" = s."id_supplier";

ALTER TABLE "TransportService" ADD COLUMN "new_id_contract" UUID;
UPDATE "TransportService" AS t SET "new_id_contract" = ct."new_id"
  FROM "Contract" AS ct WHERE t."id_contract" = ct."id_contract";

ALTER TABLE "ServiceOffered" ADD COLUMN "new_id_contract" UUID;
UPDATE "ServiceOffered" AS so SET "new_id_contract" = ct."new_id"
  FROM "Contract" AS ct WHERE so."id_contract" = ct."id_contract";

ALTER TABLE "Activity" ADD COLUMN "new_id_animal" UUID, ADD COLUMN "new_id_service" UUID;
UPDATE "Activity" AS a SET "new_id_animal" = an."new_id"
  FROM "Animal" AS an WHERE a."id_animal" = an."id_animal";
UPDATE "Activity" AS a SET "new_id_service" = so."new_id"
  FROM "ServiceOffered" AS so WHERE a."id_service" = so."id_service";

ALTER TABLE "Adoption" ADD COLUMN "new_id_animal" UUID;
UPDATE "Adoption" AS ad SET "new_id_animal" = an."new_id"
  FROM "Animal" AS an WHERE ad."id_animal" = an."id_animal";

ALTER TABLE "Donation" ADD COLUMN "new_id_animal" UUID;
UPDATE "Donation" AS d SET "new_id_animal" = an."new_id"
  FROM "Animal" AS an WHERE d."id_animal" = an."id_animal";

-- ---------------------------------------------------------------------------
-- 4. Swap the integer columns for the UUID ones
--
-- Dropping a column also drops its primary key, its SERIAL sequence and the
-- single-column indexes on it (idx_service_contract, idx_activity_service).
-- ---------------------------------------------------------------------------

-- Reference columns
ALTER TABLE "Veterinarian" DROP COLUMN "id_supplier", DROP COLUMN "id_clinic";
ALTER TABLE "Veterinarian" RENAME COLUMN "new_id_supplier" TO "id_supplier";
ALTER TABLE "Veterinarian" RENAME COLUMN "new_id_clinic" TO "id_clinic";
ALTER TABLE "Veterinarian" ALTER COLUMN "id_supplier" SET NOT NULL, ALTER COLUMN "id_clinic" SET NOT NULL;

ALTER TABLE "Contract" DROP COLUMN "id_supplier";
ALTER TABLE "Contract" RENAME COLUMN "new_id_supplier" TO "id_supplier";
ALTER TABLE "Contract" ALTER COLUMN "id_supplier" SET NOT NULL;

ALTER TABLE "TransportService" DROP COLUMN "id_contract";
ALTER TABLE "TransportService" RENAME COLUMN "new_id_contract" TO "id_contract";
ALTER TABLE "TransportService" ALTER COLUMN "id_contract" SET NOT NULL;

ALTER TABLE "ServiceOffered" DROP COLUMN "id_contract";
ALTER TABLE "ServiceOffered" RENAME COLUMN "new_id_contract" TO "id_contract";
ALTER TABLE "ServiceOffered" ALTER COLUMN "id_contract" SET NOT NULL;

ALTER TABLE "Activity" DROP COLUMN "id_animal", DROP COLUMN "id_service";
ALTER TABLE "Activity" RENAME COLUMN "new_id_animal" TO "id_animal";
ALTER TABLE "Activity" RENAME COLUMN "new_id_service" TO "id_service";
ALTER TABLE "Activity" ALTER COLUMN "id_animal" SET NOT NULL, ALTER COLUMN "id_service" SET NOT NULL;

ALTER TABLE "Adoption" DROP COLUMN "id_animal";
ALTER TABLE "Adoption" RENAME COLUMN "new_id_animal" TO "id_animal";
ALTER TABLE "Adoption" ALTER COLUMN "id_animal" SET NOT NULL;

ALTER TABLE "Donation" DROP COLUMN "id_animal";
ALTER TABLE "Donation" RENAME COLUMN "new_id_animal" TO "id_animal";
ALTER TABLE "Donation" ALTER COLUMN "id_animal" SET NOT NULL;

-- Primary key columns
ALTER TABLE "Clinic" DROP COLUMN "id_clinic";
ALTER TABLE "Clinic" RENAME COLUMN "new_id" TO "id_clinic";
ALTER TABLE "Clinic" ALTER COLUMN "id_clinic" DROP DEFAULT;

ALTER TABLE "Supplier" DROP COLUMN "id_supplier";
ALTER TABLE "Supplier" RENAME COLUMN "new_id" TO "id_supplier";
ALTER TABLE "Supplier" ALTER COLUMN "id_supplier" DROP DEFAULT;

ALTER TABLE "Contract" DROP COLUMN "id_contract";
ALTER TABLE "Contract" RENAME COLUMN "new_id" TO "id_contract";
ALTER TABLE "Contract" ALTER COLUMN "id_contract" DROP DEFAULT;

ALTER TABLE "ServiceOffered" DROP COLUMN "id_service";
ALTER TABLE "ServiceOffered" RENAME COLUMN "new_id" TO "id_service";
ALTER TABLE "ServiceOffered" ALTER COLUMN "id_service" DROP DEFAULT;

ALTER TABLE "Animal" DROP COLUMN "id_animal";
ALTER TABLE "Animal" RENAME COLUMN "new_id" TO "id_animal";
ALTER TABLE "Animal" ALTER COLUMN "id_animal" DROP DEFAULT;

ALTER TABLE "Activity" DROP COLUMN "id_activity";
ALTER TABLE "Activity" RENAME COLUMN "new_id" TO "id_activity";
ALTER TABLE "Activity" ALTER COLUMN "id_activity" DROP DEFAULT;

ALTER TABLE "Adoption" DROP COLUMN "id_adoption";
ALTER TABLE "Adoption" RENAME COLUMN "new_id" TO "id_adoption";
ALTER TABLE "Adoption" ALTER COLUMN "id_adoption" DROP DEFAULT;

ALTER TABLE "Donation" DROP COLUMN "id_donation";
ALTER TABLE "Donation" RENAME COLUMN "new_id" TO "id_donation";
ALTER TABLE "Donation" ALTER COLUMN "id_donation" DROP DEFAULT;

-- ---------------------------------------------------------------------------
-- 5. Restore primary keys, indexes and foreign keys
-- ---------------------------------------------------------------------------

ALTER TABLE "Clinic" ADD CONSTRAINT "Clinic_pkey" PRIMARY KEY ("id_clinic");
ALTER TABLE "Supplier" ADD CONSTRAINT "Supplier_pkey" PRIMARY KEY ("id_supplier");
ALTER TABLE "Veterinarian" ADD CONSTRAINT "Veterinarian_pkey" PRIMARY KEY ("id_supplier");
ALTER TABLE "Contract" ADD CONSTRAINT "Contract_pkey" PRIMARY KEY ("id_contract");
ALTER TABLE "TransportService" ADD CONSTRAINT "TransportService_pkey" PRIMARY KEY ("id_contract");
ALTER TABLE "ServiceOffered" ADD CONSTRAINT "ServiceOffered_pkey" PRIMARY KEY ("id_service");
ALTER TABLE "Animal" ADD CONSTRAINT "Animal_pkey" PRIMARY KEY ("id_animal");
ALTER TABLE "Activity" ADD CONSTRAINT "Activity_pkey" PRIMARY KEY ("id_activity");
ALTER TABLE "Adoption" ADD CONSTRAINT "Adoption_pkey" PRIMARY KEY ("id_adoption");
ALTER TABLE "Donation" ADD CONSTRAINT "Donation_pkey" PRIMARY KEY ("id_donation");

CREATE INDEX "idx_service_contract" ON "ServiceOffered"("id_contract");
CREATE INDEX "idx_activity_service" ON "Activity"("id_service");

ALTER TABLE "Veterinarian" ADD CONSTRAINT "Veterinarian_id_supplier_fkey" FOREIGN KEY ("id_supplier") REFERENCES "Supplier"("id_supplier") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Veterinarian" ADD CONSTRAINT "Veterinarian_id_clinic_fkey" FOREIGN KEY ("id_clinic") REFERENCES "Clinic"("id_clinic") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Contract" ADD CONSTRAINT "Contract_id_supplier_fkey" FOREIGN KEY ("id_supplier") REFERENCES "Supplier"("id_supplier") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "TransportService" ADD CONSTRAINT "TransportService_id_contract_fkey" FOREIGN KEY ("id_contract") REFERENCES "Contract"("id_contract") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "ServiceOffered" ADD CONSTRAINT "ServiceOffered_id_contract_fkey" FOREIGN KEY ("id_contract") REFERENCES "Contract"("id_contract") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Activity" ADD CONSTRAINT "Activity_id_animal_fkey" FOREIGN KEY ("id_animal") REFERENCES "Animal"("id_animal") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Activity" ADD CONSTRAINT "Activity_id_service_fkey" FOREIGN KEY ("id_service") REFERENCES "ServiceOffered"("id_service") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Adoption" ADD CONSTRAINT "Adoption_id_animal_fkey" FOREIGN KEY ("id_animal") REFERENCES "Animal"("id_animal") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Donation" ADD CONSTRAINT "Donation_id_animal_fkey" FOREIGN KEY ("id_animal") REFERENCES "Animal"("id_animal") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ---------------------------------------------------------------------------
-- 6. String enumerations -> SMALLINT (values mirror packages/schemas/src/enums.ts)
--
-- The old CHECK constraints guaranteed only these strings exist, so every row
-- maps. Defaults are dropped before the type change because 'Active' /
-- 'available' cannot be cast to SMALLINT. The indexes on these columns are
-- rebuilt automatically by ALTER COLUMN ... TYPE.
-- ---------------------------------------------------------------------------

ALTER TABLE "Supplier" DROP CONSTRAINT "Supplier_type_check";
ALTER TABLE "Contract" DROP CONSTRAINT "Contract_contract_category_check";
ALTER TABLE "Contract" DROP CONSTRAINT "Contract_status_check";
ALTER TABLE "Animal" DROP CONSTRAINT "Animal_status_check";

-- SupplierType: 1 Veterinarian, 2 Food Company, 3 Service Company
ALTER TABLE "Supplier" ALTER COLUMN "type" TYPE SMALLINT USING (
  CASE "type"
    WHEN 'Veterinarian' THEN 1
    WHEN 'Food Company' THEN 2
    WHEN 'Service Company' THEN 3
  END
);

-- ContractCategory: 1 Veterinarian, 2 Food, 3 Service
ALTER TABLE "Contract" ALTER COLUMN "contract_category" TYPE SMALLINT USING (
  CASE "contract_category"
    WHEN 'Veterinarian' THEN 1
    WHEN 'Food' THEN 2
    WHEN 'Service' THEN 3
  END
);

-- ContractStatus: 1 Active, 2 Inactive, 3 Expired
ALTER TABLE "Contract" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Contract" ALTER COLUMN "status" TYPE SMALLINT USING (
  CASE "status"
    WHEN 'Active' THEN 1
    WHEN 'Inactive' THEN 2
    WHEN 'Expired' THEN 3
  END
);
ALTER TABLE "Contract" ALTER COLUMN "status" SET DEFAULT 1;

-- AnimalStatus: 1 Available, 2 Adopted, 3 Reserved, 4 Deceased
ALTER TABLE "Animal" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Animal" ALTER COLUMN "status" TYPE SMALLINT USING (
  CASE "status"
    WHEN 'available' THEN 1
    WHEN 'adopted' THEN 2
    WHEN 'reserved' THEN 3
    WHEN 'deceased' THEN 4
  END
);
ALTER TABLE "Animal" ALTER COLUMN "status" SET DEFAULT 1;

ALTER TABLE "Supplier" ADD CONSTRAINT "Supplier_type_check"
  CHECK ("type" IN (1, 2, 3));

ALTER TABLE "Contract" ADD CONSTRAINT "Contract_contract_category_check"
  CHECK ("contract_category" IN (1, 2, 3));

ALTER TABLE "Contract" ADD CONSTRAINT "Contract_status_check"
  CHECK ("status" IN (1, 2, 3));

ALTER TABLE "Animal" ADD CONSTRAINT "Animal_status_check"
  CHECK ("status" IN (1, 2, 3, 4));
